language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
r_packages:
  - nlme
r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/networkDynamic
- statnet/ergm
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false