language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
r_github_packages:
- statnet/ergm@3.11
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: true
